/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as ProdukRouteImport } from './routes/produk'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminProfilRouteImport } from './routes/admin.profil'
import { Route as AdminProdukListRouteImport } from './routes/admin.produk-list'
import { Route as AdminProdukRouteImport } from './routes/admin.produk'
import { Route as AdminPesanRouteImport } from './routes/admin.pesan'
import { Route as AdminLayananRouteImport } from './routes/admin.layanan'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukRoute = ProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilRoute = AdminProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdukListRoute = AdminProdukListRouteImport.update({
  id: '/produk-list',
  path: '/produk-list',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdukRoute = AdminProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPesanRoute = AdminPesanRouteImport.update({
  id: '/pesan',
  path: '/pesan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayananRoute = AdminLayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/produk': typeof ProdukRoute
  '/tentang': typeof TentangRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/pesan': typeof AdminPesanRoute
  '/admin/produk': typeof AdminProdukRoute
  '/admin/produk-list': typeof AdminProdukListRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/produk': typeof ProdukRoute
  '/tentang': typeof TentangRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/pesan': typeof AdminPesanRoute
  '/admin/produk': typeof AdminProdukRoute
  '/admin/produk-list': typeof AdminProdukListRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/produk': typeof ProdukRoute
  '/tentang': typeof TentangRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/pesan': typeof AdminPesanRoute
  '/admin/produk': typeof AdminProdukRoute
  '/admin/produk-list': typeof AdminProdukListRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/kontak'
    | '/layanan'
    | '/produk'
    | '/tentang'
    | '/admin/layanan'
    | '/admin/pesan'
    | '/admin/produk'
    | '/admin/produk-list'
    | '/admin/profil'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kontak'
    | '/layanan'
    | '/produk'
    | '/tentang'
    | '/admin/layanan'
    | '/admin/pesan'
    | '/admin/produk'
    | '/admin/produk-list'
    | '/admin/profil'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/kontak'
    | '/layanan'
    | '/produk'
    | '/tentang'
    | '/admin/layanan'
    | '/admin/pesan'
    | '/admin/produk'
    | '/admin/produk-list'
    | '/admin/profil'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  KontakRoute: typeof KontakRoute
  LayananRoute: typeof LayananRoute
  ProdukRoute: typeof ProdukRoute
  TentangRoute: typeof TentangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk': {
      id: '/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof ProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profil': {
      id: '/admin/profil'
      path: '/profil'
      fullPath: '/admin/profil'
      preLoaderRoute: typeof AdminProfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produk-list': {
      id: '/admin/produk-list'
      path: '/produk-list'
      fullPath: '/admin/produk-list'
      preLoaderRoute: typeof AdminProdukListRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produk': {
      id: '/admin/produk'
      path: '/produk'
      fullPath: '/admin/produk'
      preLoaderRoute: typeof AdminProdukRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pesan': {
      id: '/admin/pesan'
      path: '/pesan'
      fullPath: '/admin/pesan'
      preLoaderRoute: typeof AdminPesanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/layanan': {
      id: '/admin/layanan'
      path: '/layanan'
      fullPath: '/admin/layanan'
      preLoaderRoute: typeof AdminLayananRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLayananRoute: typeof AdminLayananRoute
  AdminPesanRoute: typeof AdminPesanRoute
  AdminProdukRoute: typeof AdminProdukRoute
  AdminProdukListRoute: typeof AdminProdukListRoute
  AdminProfilRoute: typeof AdminProfilRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayananRoute: AdminLayananRoute,
  AdminPesanRoute: AdminPesanRoute,
  AdminProdukRoute: AdminProdukRoute,
  AdminProdukListRoute: AdminProdukListRoute,
  AdminProfilRoute: AdminProfilRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  KontakRoute: KontakRoute,
  LayananRoute: LayananRoute,
  ProdukRoute: ProdukRoute,
  TentangRoute: TentangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
